### ISSUE TITLE
报错了，问下开发时node版本使用的是多少版本？

### ISSUE THREAD

**Issue by liyinchigithub** [yudaocode/yudao-ui-admin-vue2#1]
<img width="683" alt="image" src="https://github.com/yudaocode/yudao-ui-admin-vue2/assets/19643260/4c2b6cb2-2219-41db-a326-b833a406e90c">
<img width="793" alt="image" src="https://github.com/yudaocode/yudao-ui-admin-vue2/assets/19643260/91caf65e-83db-4eb2-b13b-bcd277f0dfc5">

**Comment by liyinchigithub** [comment]
v16.14.2

**Comment by YunaiV** [comment]
node12
