### ISSUE TITLE
项目起不起来，卡在68%

### ISSUE THREAD

**Issue by liyinchigithub** [yudaocode/yudao-ui-admin-vue2#2]
nodejs 12.22
npm run dev
68% building 3403/3470 modules 67 active .../yudao-ui-admin-vue2/src/components/bpmnProcessDesigner/package/palette/ProcessPalette.vue?vue&type=style&index=0&id=ad2b6d86&scoped=true&lang=scss&

**Comment by 18722650553** [comment]
me too,i have a desc error!
Syntax Error: D:\Git_yudao\Git_yudao-ui-admin-vue2\src\views\system\user\profile\userSocial.vue: Unexpected token, expected "," (1:8)

> 1 | [object Promise]
    |         ^
  2 | export { render, staticRenderFns }
    at parser.next (<anonymous>)
    at normalizeFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)


 @ ./src/views/system/user/profile/userSocial.vue?vue&type=template&id=34c563bc& 1:0-557 1:0-557
 @ ./src/views/system/user/profile/userSocial.vue
 @ ./src/views sync ^\.\/.*$
 @ ./src/store/modules/permission.js
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.110.5:80&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by YunaiV** [comment]
测试了下，使用 node12 没问题哈。
